services:
  - type: web
    name: o-engracadao
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: BOT_KEY
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
      - key: TARGET_USER_ID
        sync: false
      - key: CRON_SCHEDULE
        sync: false